[package]
name = "zbus_names"
version = "3.0.0"
authors = ["Zeeshan Ali Khan <zeeshanak@gnome.org>"]
edition = "2021"
rust-version = "1.81"

description = "A collection of D-Bus bus names types"
repository = "https://github.com/dbus2/zbus/"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["os::unix-apis"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.200", features = ["derive"] }
zvariant = { path = "../zvariant", version = "4.0.0", default-features = false, features = [
    "enumflags2",
] }
static_assertions = "1.1.0"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

