[package]
name = "zbus_names"
version = "2.3.0"
authors = ["Zeeshan Ali Khan <zeeshanak@gnome.org>"]
edition = "2018"
rust-version = "1.60"

description = "A collection of D-Bus bus names types"
repository = "https://gitlab.freedesktop.org/dbus/zbus/"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["os::unix-apis"]
readme = "README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zvariant = { path = "../zvariant", version = "3.9", default-features = false, features = ["enumflags2"] }
static_assertions = "1.1.0"

[dev-dependencies]
doc-comment = "0.3.3"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
